name: Build
on:
  schedule:
    - cron:  '0 0 1 1 *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.1.0
      - name: Build the app
        run: ./gradlew build
